# Common Settings

# To enable Floor Line Eighths block's hard-coded loot table. Accept one of
# the following values:
# true | yes | always - Always enabled.
# auto | null - Enabled when loot table
# regedt32:blocks/cntrafficsymbols/floor_line_eighths is absent, disabled
# otherwise.
# false | no | never - Always disabled.
hardcoded_floor_line_eighths_loot_enabled=auto
