# Before modifying
#
# To modify this file within the jar takes no effect; in order to apply your
# changes, you have to copy this file to ${GAMEDIR}/config/.

# Common Settings

# To enable Floor Line Eighths block's hard-coded loot table. Accept one of
# the following values:
# true | yes | always - Always enabled.
# auto | null - Enabled when loot table
# regedt32:blocks/cntrafficsymbols/floor_line_eighths is absent, disabled
# otherwise.
# false | no | never - Always disabled.
hardcoded_floor_line_eighths_loot_enabled=auto
# To set the whether the blocks added by this mod have a "waterlogged"
# property. Accept true or false.
waterlogged_property=true
# To enable Barricades 1 block's hard-coded loot table. Accept one of the
# following values:
# true | yes | always - Always enabled.
# auto | null - Enabled when loot table
# regedt32:blocks/cntrafficsymbols/barricades_1 is absent, disabled otherwise.
# false | no | never - Always disabled.
hardcoded_barricades_1_loot_enabled=auto
