EX=b"""{
  "parent": "minecraft:recipes/root",
  "criteria": {
    "has_%s": {
      "conditions": {"items": [{"items": ["%s"]}]},
      "trigger": "minecraft:inventory_changed"
    },
    "has_the_recipe": {
      "conditions": {"recipe": "regedt32:cntrafficsymbols/%s"},
      "trigger": "minecraft:recipe_unlocked"
    }
  },
  "requirements": [
    [
      "has_the_recipe",
      "has_%s"
    ]
  ],
  "rewards": {"recipes": ["regedt32:cntrafficsymbols/%s"]},
  "sends_telemetry_event": false
}
""".replace(b"\n",b"\r\n")
D={
 b"circle_backboard": b"regedt32:cntrafficsymbols/iron_plate",
 b"iron_plate_from_iron_ingot_stonecutting": b"minecraft:iron_ingot",
 b"iron_plate": b"minecraft:iron_block",
 b"lift_speedlimit_high_100": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_105": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_10": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_110": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_115": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_120": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_125": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_130": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_135": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_140": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_145": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_150": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_15": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_20": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_25": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_30": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_35": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_3": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_40": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_45": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_50": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_55": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_5": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_60": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_65": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_70": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_75": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_80": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_85": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_90": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_95": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"lift_speedlimit_high_special": b"regedt32:cntrafficsymbols/lift_speedlimit_high_special",
 b"speedlimit_high_100": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_105": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_10": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_110": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_115": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_120": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_125": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_130": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_135": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_140": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_145": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_150": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_15": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_20": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_25": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_30": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_35": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_3": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_40": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_45": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_50": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_55": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_5": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_60": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_65": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_70": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_75": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_80": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_85": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_90": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_95": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_high_special": b"regedt32:cntrafficsymbols/speedlimit_high_special",
 b"speedlimit_low_100": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_105": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_10": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_110": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_115": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_120": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_125": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_130": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_135": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_140": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_145": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_150": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_15": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_20": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_25": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_30": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_35": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_3": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_40": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_45": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_50": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_55": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_5": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_60": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_65": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_70": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_75": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_80": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_85": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_90": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_95": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low": b"regedt32:cntrafficsymbols/speedlimit_low_special",
 b"speedlimit_low_special": b"regedt32:cntrafficsymbols/speedlimit_low_special"
}
for k,v in D.items():
 s=v.replace(b":",b"/").split(b"/")[-1]
 with open(f"{k.decode()}.json","wb")as f:f.write(EX%(s,v,k,s,k))